### ISSUE TITLE
GLEP 81 tracker

### ISSUE THREAD

**Issue by xmhd** [adjust/gentoo-overlay#559]
[https://www.gentoo.org/glep/glep-0081.html](url)

GLEP 81 in Gentoo Linux brought in management of users + groups by dedicated packages. Packages should be transitioned to this as opposed to continuing to use enewuser and enewgroup.

This issue shall serve as the tracker for discussing migration and tracking progress.

Some of these packages will already be assigned a user + group ID upstream at Gentoo. We should stay 1:1 with those where possible. For packages which are not, we should check what other Linux distributions / BSDs are assigning.

note: some of these packages can most likely be purged from the overlay which will make our lives easier.

Packages in ::adjust which are currently affected and require migration:

- [X] app-admin/consul-bin: GID 411 UID 411 (Gentoo)
- [X] app-admin/schaufel: GID 997 UID 997
- [X] app-metrics/prometheus: GID 430 UID 430 (Gentoo)
- [X] app-metrics/statsd-explorer
- [X] app-misc/elasticsearch: GID 183 UID 183 (Gentoo)
- [ ] app-misc/go-carbon
- [X] app-misc/karmabot-bin GID 114 UID 114 - most commonly recurring ID in our infrastructure
- [X] app-misc/logstash: GID 270 UID 270 (Gentoo)
- [X] dev-db/aerospike-server-enterprise GID 118 UID 118 - most commonly recurring ID in our infrastructure
- [X] dev-db/clickhouse: GID 998 UID 998 - most commonly recurring ID in our infrastructure
- [X] dev-db/metabase-bin GID 999 UID 999 - most commonly recurring ID in our infrastructure
- [X] net-analyzer/clickhouse_exporter GID 109 UID 109 - most commonly recurring ID in our infrastructure
- [X] net-analyzer/nmis GID 119 UID 119 - most commonly recurring ID in our infrastructure
- [X] net-analyzer/postgresql_exporter
- [X] net-analyzer/prometheus GID 430 UID 430 (Gentoo)
- [X] net-analyzer/prometheus-postgres_exporter
- [X] net-analyzer/zabbix GID 329 UID 329 (Gentoo)
- [X] sys-cluster/ceph: GID 267 UID 267 (Gentoo)
- [X] sys-cluster/chronos-bin GID 2000 UID 2000 - most commonly recurring ID in our infrastructure
- [X] sys-cluster/flink-bin GID 5013 UID 5013 - most commonly recurring ID in our infrastructure
- [X] sys-cluster/hive-standalone-metastore-bin
- [X] sys-cluster/mesos GID 2000 UID 2000 - most commonly recurring ID in our infrastructure
- [ ] sys-cluster/nomad-bin -- source package now maintained @ Gentoo - REMOVE?
- [X] sys-cluster/spark-bin GID 2000 UID 2000 - most commonly recurring ID in our infrastructure
- [X] www-apps/kibana-bin: GID 269 UID 269 (Gentoo)
- [X] www-apps/shiny-server GID 125 UID 125 - most commonly recurring ID in our infrastructure
